// front/src/components/Counter.vue
<template>
  <div class="test">Counter {{ $count }}</div>
  <button @click="incrementCounter">+1</button>
</template>
<script setup>
  import { ref } from "vue"
  
  import {count} from '../stores/count'
  import {useStore} from '@nanostores/vue'
  const $count = useStore(count)

  const incrementCounter = () => {
    count.set($count.value +1) 
  }
</script>

// front/src/components/Counter.tsx
import React, { useState } from "react"
import {count} from '../stores/count'
import {useStore} from '@nanostores/react'

export default function Example() {
  // Declaración de una variable de estado que llamaremos "count"  const [count, setCount] = useState(0);
  // const [count, setCount] = useState(0)
  const $count = useStore(count)
  return (
    <div>
      <p>You clicked {$count} times</p>
      <button onClick={() => count.set($count + 1)}>Click me</button>
    </div>
  )
}
